trigger: none

resources:
  pipelines:
  - pipeline: buildArtifact
    source: Task19-Build
    trigger: true

pool:
  name: batch13-pool

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    steps:

    - download: buildArtifact
      artifact: app
      displayName: Download Artifact

    - bash: |
        echo "Deploying artifact..."
        test -f "$(Pipeline.Workspace)/buildArtifact/app/index.html"
        echo "Artifact found"
        echo "Deployment successful"
      displayName: Deploy