trigger:
- main

pool:
  name: batch13-pool

stages:

- stage: Build
  jobs:
  - job: Build
    steps:

    - bash: |
        echo "Building application..."
        mkdir -p "$(Build.ArtifactStagingDirectory)/app"
        cp index.html "$(Build.ArtifactStagingDirectory)/app/"
      displayName: Build

    - bash: |
        chmod +x test.sh
        ./test.sh
      displayName: Test

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/app'
        artifact: 'app'
      displayName: Publish Artifact
