trigger: none

resources:
  pipelines:
  - pipeline: buildPipeline
    source: Task19-Build
    trigger: true

pool:
  name: batch13-pool

stages:

- stage: Deploy
  jobs:
  - job: Deploy
    steps:

    - download: buildPipeline
      artifact: app
      displayName: Download Artifact

    - bash: |
        echo "Deploying artifact..."

        test -f "$(Pipeline.Workspace)/buildPipeline/app/index.html"

        echo "Artifact found"
        echo "Deployment successful"
      displayName: Deploy
